project:
  type: book
  output-dir: docs

book:
  title: "Análise de Sobrevivência"
  subtitle: "Iniciação Ciêntifica - PIBIC 2024/2025 (UFPA)"
  date: "01/25/2024"
  
  author:
    
    name: "**Breno Cauã Rodrigues da Silva**"
    orcid: 0009-0005-9740-2069
    corresponding: true
    affiliations:
      - name: "Universidade Federal do Pará"
      - name: "Instituto de Ciências Exatas e Naturais"
      - name: "Falculdade de Estatística"
      
  page-footer:
    left: |
      **SILVA, B.C.R**
    right: |
      Construído <a href="https://quarto.org/"> Pacote Quarto no R4.3</a>.
  repo-url : https://github.com/csilv7/ANALISE_DE_SOBREVIVENCIA
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  page-navigation: true
  chapters:
    - index.qmd
    - CI_CONC_BASIC.qmd
    - CII_TEC_N_PARAM.qmd
    - CIII_TEC_PARAM.qmd
    - CIV_MTVA.qmd
    - references.qmd

comments:
  hypothesis: true

bibliography: references.bib


format:
  html:
    number-sections: true
    df-print: paged
    theme:
      light: [blue,custom.scss]
      dark:  [cyborg,custom.scss]
    code-fold: true
    code-tools: true
    code-link: true
    toc-title: Índice
    toc-location: right
  pdf:
    documentclass: scrreprt
    fig-pos: "H"
    number-sections: true
    pdf-engine: xelatex
    fontsize: 12pt
    geometry: margin=2.5cm
    echo: false
  docx:
    number-sections: true

execute:
  echo: true

lang: pt