```{=html}
<style>
  body{text-align: justify}
</style>
```

:::: progress
::: {.progress-bar style="width: 100%;"}
:::
::::

# Modelos de Tempo de Vida Acelerado

## Introdução

## Distribuição Exponencial

Em modelos de tempo de vida acelerados a distribuição exponencial tem densidade expressa por:

$$
f(t) = \alpha \exp\left\{ - \alpha \left( \dfrac{t}{\exp\{\mathbf{x'}\boldsymbol{\beta}\}} \right) \right\}.
$$ {#eq-densitExpMTVA}

A partir de @eq-densitExpMTVA pode-se obter a função de sobrevivência, dada por:

$$
S(t) = \exp\left\{ - \alpha \left( \dfrac{t}{\exp\{\mathbf{x'}\boldsymbol{\beta}\}} \right) \right\}.
$$ {#eq-StExpMTVA}

Desta forma, é possível chegar na função de log-verossimilhança dada pela @eq-logVerExpMTVA para MTVA da distribuição exponencial.

$$
l(\theta) = \ln[\alpha] \sum_{i = 1}^{n} \delta_{i} - \alpha \sum_{i = 1}^{n} \dfrac{t_{i}}{\exp\{\mathbf{x'}_{i}\boldsymbol{\beta}\}},
$$ {#eq-logVerExpMTVA}

onde $\theta = (\alpha, \beta_{0}, \beta_{1}, \ldots, \beta_{p})$. Toma-se as derivadas parciais em relação a cada parâmetro deste modelo, desta forma, tem-se:

$$
\dfrac{\partial l(\theta)}{\partial \alpha} = \dfrac{1}{\alpha} \sum_{i = 1}^{n} \delta_{i} - \sum_{i = 1}^{n} \dfrac{t_{i}}{\exp\{\mathbf{x'}_{i}\boldsymbol{\beta}\}},
$$

para $\beta_{0}$, temos:

$$
\dfrac{\partial l(\theta)}{\partial \beta_{0}} = \alpha \sum_{i = 1}^{n} \dfrac{t_{i}}{\exp\{\mathbf{x'}_{i}\boldsymbol{\beta}\}}.
$$

Para qualquer outro coeficiente $\beta_{k}$, derivando, temos:

$$
\dfrac{\partial l(\theta)}{\partial \beta_{k}} = - \alpha \sum_{i = 1}^{n} \frac{\partial}{\partial \beta_{k}} \left[ \frac{t_{i}}{\exp\{\mathbf{x'}\boldsymbol{\beta}\}} \right] = - \alpha \sum_{i = 1}^{n} - \frac{t_{i} x_{ki}}{\exp\{\mathbf{x'}\boldsymbol{\beta}\}} = \alpha \sum_{i = 1}^{n} \frac{t_{i} x_{ki}}{\exp\{\mathbf{x'}\boldsymbol{\beta}\}}.
$$
Para obter as estimativas para o vetor de parâmetros $\theta$ temos que utilizar algum método numérico, pois não a solução análitico para as funções (não lineares) resultantes das derivadas.

## Distribuição Weibull

:::: progress
::: {.progress-bar style="width: 100%;"}
:::
::::
